=== acumos/license-manager/license-manager-client-library/src/main/resources/schema/1.0.0/license-profile.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "version": "1.0.0",
  "required": [
    "$schema",
    "keyword",
    "licenseName",
    "copyright",
    "rtuRequired"
  ],
  "properties": {
    "$schema": {
      "type": "string",
      "default": "https://raw.githubusercontent.com/acumos/license-manager/master/license-manager-client-library/src/main/resources/schema/1.0.0/license-profile.json"
    },
    "keyword": {
      "type": "string"
    },
    "licenseName": {
      "type": "string"
    },
    "intro": {
      "type": "string"
    },
    "copyright": {
      "type": "object",
      "required": [
        "year",
        "company",
        "suffix"
      ],
      "properties": {
        "year": {
          "type": "integer",
          "default": 2019
        },
        "company": {
          "type": "string"
        },
        "suffix": {
          "type": "string"
        }
      }
    },
    "softwareType": {
      "type": "string"
    },
    "companyName": {
      "type": "string"
    },
    "contact": {
      "type": "object",
      "required": [
        "name",
        "URL",
        "email"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "URL": {
          "type": "string"
        },
        "email": {
          "type": "string"
        }
      }
    },
    "additionalInfo": {
      "type": "string"
    },
    "rtuRequired":{
      "type": "boolean",
      "description": "When true a right to use must be provided by the supplier to enable use."
    }
  }
}

=== acumos/license-manager/license-profile-editor/src/assets/examples/vendor-a-oss.json
{
  "$schema": "https://raw.githubusercontent.com/acumos/license-manager/master/license-manager-client-library/src/main/resources/schema/1.0.0/license-profile.json",
  "keyword": "Vendor-A-OSS",
  "licenseName": "Vendor A Open Source Software License",
  "copyright": {
    "year": 2019,
    "company": "Vendor A",
    "suffix": "All Rights Reserved"
  },
  "softwareType": "Machine Learning Model",
  "companyName": "Vendor A",
  "contact": {
    "name": "Vendor A Team",
    "URL": "http://Vendor-A.com",
    "email": "support@Vendor-A.com"
  },
  "additionalInfo": "http://Vendor-A.com/licenses/Vendor-A-OSS",
  "rtuRequired": true
}

=== acumos/license-manager/license-manager-client-library/src/test/resources/partial-license.json
{
  "$schema": "/schema/1.0.0/license-profile.json",
  "keyword": "Apache-2.0",
  "licenseName": "Apache 2.0",
  "copyright": {
    "year": 2019,
    "company": "Company A",
    "suffix": "A Intellectual Property. All rights reserved."
  },
  "softwareType": "Acumos Ai/ML Model",
  "companyName": "Acumos",
  "contact": {
    "name": "Acumos HelpDesk",
    "URL": "https://marketplace.acumos.org",
    "email": "contact@.acumos.org"
  },
  "rtuRequired": true
}
