=== acumos/license-manager/license-manager-client-library/src/main/resources/license-profile.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "required": [
    "keyword",
    "licenseName",
    "copyright"
  ],
  "properties": {
    "keyword": {
      "type": "string"
    },
    "licenseName": {
      "type": "string"
    },
    "intro": {
      "type": "string"
    },
    "copyright": {
      "type": "object",
      "required": [
        "year",
        "company",
        "suffix"
      ],
      "properties": {
        "year": {
          "type": "integer",
          "default": 2019
        },
        "company": {
          "type": "string"
        },
        "suffix": {
          "type": "string"
        }
      }
    },
    "softwareType": {
      "type": "string"
    },
    "companyName": {
      "type": "string"
    },
    "contact": {
      "type": "object",
      "required": [
        "name",
        "URL",
        "email"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "URL": {
          "type": "string"
        },
        "email": {
          "type": "string"
        }
      }
    },
    "additionalInfo": {
      "type": "string"
    }
  }
}

=== acumos/license-manager/license-manager-client-library/src/test/resources/license.json
{
  "$schema": "/schema/1.0.0/license-profile.json",
  "keyword": "Apache-2.0",
  "licenseName": "Apache 2.0",
  "intro": "This Acumos software file is distributed by Nordix Foundation under the Apache License, Version 2.0 (the \"License\"); you may not use this file except in compliance with the License. You may obtain a copy of the License at",
  "copyright": {
    "year": 2019,
    "company": "Company A",
    "suffix": "A Intellectual Property. All rights reserved."
  },
  "softwareType": "Acumos Ai/ML Model",
  "companyName": "Acumos",
  "contact": {
    "name": "Acumos HelpDesk",
    "URL": "https://marketplace.acumos.org",
    "email": "contact@.acumos.org"
  },
  "additionalInfo": "This Acumos software file is distributed by Nordix Foundation under the Apache License, Version 2.0 (the \"License\"); you may not use this file except in compliance with the License. You may obtain a copy of the License at"
}

=== acumos/license-manager/license-profile-editor/src/assets/examples/apache-2.0-company-a.json
{
  "keyword": "Apache-2.0",
  "licenseName": "Apache License 2.0",
  "copyright": {
    "year": 2019,
    "company": "Company A",
    "suffix": "All Rights Reserved"
  },
  "softwareType": "Machine Learning Model",
  "companyName": "Company A",
  "contact": {
    "name": "Company A  Team Member",
    "URL": "http://companya.com",
    "email": "support@companya.com"
  }
}
